stages:
  - name: "train"
    epochs: 100

    model: "apps.cifar10_demo.model.CIFAR10Model"
    model_args:
      num_classes: 10
      dropout_rate: 0.5

    criterion: "cvtrainer.loss.CrossEntropyLoss"

    optimizer:
      type: "SGD"
      kwargs:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0005
      layerwise:
        backbone: 0.1
        adapter: 0.1
        head: 0.1

    dataloader:
      train:
        dataset:
          type: "apps.cifar10_demo.dataset.CIFAR10DataAdapter"
          args:
            data_path: "./data/cifar10"
            train: true

        transforms:
          backend: "Albumentations"
          transforms:
            - type: "Resize"
              kwargs:
                height: 32
                width: 32
            - type: "HorizontalFlip"
              kwargs:
                p: 0.5
            - type: "RandomRotate90"
              kwargs:
                p: 0.5

        tensorizer:
          type: "cvtrainer.data.tensorizer.Tensorizer"
          mapping:
            x:
              type: "cvtrainer.data.tensorizer.ImageTensorizer"
              kwargs:
                normalize:
                  mean: [0.4914, 0.4822, 0.4465]
                  std: [0.2023, 0.1994, 0.2010]
                dtype: float
            class_id:
              type: "cvtrainer.data.tensorizer.OneHotTensorizer"
              kwargs:
                num_classes: 10
                dtype: long

        dataloader_args:
          batch_size: 128
          num_workers: 4
          shuffle: true
          collate_fn: "cvtrainer.data.collate.default_collate_fn"

      val:
        dataset:
          type: "apps.cifar10_demo.dataset.CIFAR10DataAdapter"
          args:
            data_path: "./data/cifar10"
            train: false

        transforms:
          backend: "Albumentations"
          transforms:
            - type: "Resize"
              kwargs:
                height: 32
                width: 32

        tensorizer:
          type: "cvtrainer.data.tensorizer.Tensorizer"
          mapping:
            x:
              type: "cvtrainer.data.tensorizer.ImageTensorizer"
              kwargs:
                normalize:
                  mean: [0.4914, 0.4822, 0.4465]
                  std: [0.2023, 0.1994, 0.2010]
                dtype: float
            class_id:
              type: "cvtrainer.data.tensorizer.OneHotTensorizer"
              kwargs:
                num_classes: 10
                dtype: long

        dataloader_args:
          batch_size: 128
          num_workers: 4
          shuffle: false
          collate_fn: "cvtrainer.data.collate.default_collate_fn"

    hooks:
      - type: "cvtrainer.hooks.LRSchedulerHook"
        kwargs:
          scheduler_type: "MultiStepLR"
          scheduler_kwargs:
            milestones: [50, 75]
            gamma: 0.1
      - type: "cvtrainer.hooks.CheckpointHook"
        kwargs:
          save_dir: "./checkpoints/cifar10"
          save_freq: 10

    meters:
      - type: "cvtrainer.meters.LossMeter"
      - type: "cvtrainer.meters.AccuracyMeter"
        kwargs:
          topk: [1, 5]
